### ISSUE TITLE
Issue running on OS X

### ISSUE THREAD

**Issue by jacob-ebey** [jacob-ebey/mwap#5]
Couldn't get the CLI to run on OSX until i opened `node_modules/.bin/mwap` and switched the line endings from CRLF to LF.

https://twitter.com/tunderadev/status/1390788728537288704

**Comment by tundera** [comment]
So I haven't tried this before myself, but it seems to be specific to using git on Windows. I found [this article on github's docs](https://docs.github.com/en/github/getting-started-with-github/configuring-git-to-handle-line-endings) that explains it a bit better, but from what I got out of it:

- Unix and Windows have different ways of expressing line endings (LF format for Unix, CRLF for Windows)
- Git lets you specify how to handle line endings **globally** on your machine via `git config --global core.autocrlf` (e.g. `git config --global core.autocrlf true` to allow compatibility with Unix)
- Git also lets you specify the setting **locally** via a `.gitattributes` folder

I'll submit a PR to add a `.gitattributes` file that should fix it 🤞.  I think you might see this issue on other repos you push to github from your machine if your global git setting for `core.autocrlf` is unset or set to force CRLF format line endings.

**Comment by jacob-ebey** [comment]
I've added prettier and published v0.0.4. I'm about to test it out on a Mac and see if that did it.

**Comment by jacob-ebey** [comment]
Seems to have done it for me. 🚀

**Comment by tundera** [comment]
@jacob-ebey Yep upgraded to v0.0.4 and it's working 😄
